// Generated by gencpp from file HW4/First_srvRequest.msg
// DO NOT EDIT!


#ifndef HW4_MESSAGE_FIRST_SRVREQUEST_H
#define HW4_MESSAGE_FIRST_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace HW4
{
template <class ContainerAllocator>
struct First_srvRequest_
{
  typedef First_srvRequest_<ContainerAllocator> Type;

  First_srvRequest_()
    : srv(0)
    , val(0)  {
    }
  First_srvRequest_(const ContainerAllocator& _alloc)
    : srv(0)
    , val(0)  {
  (void)_alloc;
    }



   typedef int32_t _srv_type;
  _srv_type srv;

   typedef int32_t _val_type;
  _val_type val;





  typedef boost::shared_ptr< ::HW4::First_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::HW4::First_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct First_srvRequest_

typedef ::HW4::First_srvRequest_<std::allocator<void> > First_srvRequest;

typedef boost::shared_ptr< ::HW4::First_srvRequest > First_srvRequestPtr;
typedef boost::shared_ptr< ::HW4::First_srvRequest const> First_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::HW4::First_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::HW4::First_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace HW4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::HW4::First_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::HW4::First_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HW4::First_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::HW4::First_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HW4::First_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::HW4::First_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::HW4::First_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcd40c77c15ddc2db88f3e8277b151b3";
  }

  static const char* value(const ::HW4::First_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcd40c77c15ddc2dULL;
  static const uint64_t static_value2 = 0xb88f3e8277b151b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::HW4::First_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HW4/First_srvRequest";
  }

  static const char* value(const ::HW4::First_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::HW4::First_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 srv\n\
int32 val\n\
";
  }

  static const char* value(const ::HW4::First_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::HW4::First_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.srv);
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct First_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::HW4::First_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::HW4::First_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "srv: ";
    Printer<int32_t>::stream(s, indent + "  ", v.srv);
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW4_MESSAGE_FIRST_SRVREQUEST_H
