// Generated by gencpp from file HW4/First_srv.msg
// DO NOT EDIT!


#ifndef HW4_MESSAGE_FIRST_SRV_H
#define HW4_MESSAGE_FIRST_SRV_H

#include <ros/service_traits.h>


#include <HW4/First_srvRequest.h>
#include <HW4/First_srvResponse.h>


namespace HW4
{

struct First_srv
{

typedef First_srvRequest Request;
typedef First_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct First_srv
} // namespace HW4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::HW4::First_srv > {
  static const char* value()
  {
    return "f8869d9badbe825e7bdab772d9d5e138";
  }

  static const char* value(const ::HW4::First_srv&) { return value(); }
};

template<>
struct DataType< ::HW4::First_srv > {
  static const char* value()
  {
    return "HW4/First_srv";
  }

  static const char* value(const ::HW4::First_srv&) { return value(); }
};


// service_traits::MD5Sum< ::HW4::First_srvRequest> should match 
// service_traits::MD5Sum< ::HW4::First_srv > 
template<>
struct MD5Sum< ::HW4::First_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::HW4::First_srv >::value();
  }
  static const char* value(const ::HW4::First_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::HW4::First_srvRequest> should match 
// service_traits::DataType< ::HW4::First_srv > 
template<>
struct DataType< ::HW4::First_srvRequest>
{
  static const char* value()
  {
    return DataType< ::HW4::First_srv >::value();
  }
  static const char* value(const ::HW4::First_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::HW4::First_srvResponse> should match 
// service_traits::MD5Sum< ::HW4::First_srv > 
template<>
struct MD5Sum< ::HW4::First_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::HW4::First_srv >::value();
  }
  static const char* value(const ::HW4::First_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::HW4::First_srvResponse> should match 
// service_traits::DataType< ::HW4::First_srv > 
template<>
struct DataType< ::HW4::First_srvResponse>
{
  static const char* value()
  {
    return DataType< ::HW4::First_srv >::value();
  }
  static const char* value(const ::HW4::First_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW4_MESSAGE_FIRST_SRV_H
